#!/bin/bash
# Quick Docker Build Commands for MATHIA

echo "🚀 MATHIA Docker Build Optimizer"
echo "=================================="
echo ""
echo "1️⃣  FAST BUILD (recommended):"
echo "   DOCKER_BUILDKIT=1 docker-compose build --no-cache"
echo ""
echo "2️⃣  STANDARD BUILD (uses cache):"
echo "   docker-compose build"
echo ""
echo "3️⃣  START SERVICES:"
echo "   docker-compose up"
echo ""
echo "4️⃣  START IN BACKGROUND:"
echo "   docker-compose up -d"
echo ""
echo "5️⃣  RUN MIGRATIONS:"
echo "   docker-compose exec web python manage.py migrate"
echo ""
echo "6️⃣  CREATE SUPERUSER:"
echo "   docker-compose exec web python manage.py createsuperuser"
echo ""
echo "7️⃣  VIEW LOGS:"
echo "   docker-compose logs -f web"
echo ""
echo "8️⃣  STOP ALL SERVICES:"
echo "   docker-compose down"
echo ""
echo "9️⃣  CLEAN UP (remove volumes too):"
echo "   docker-compose down -v"
echo ""
echo "🔟 PRUNE UNUSED DOCKER RESOURCES:"
echo "   docker system prune -a"
echo ""
echo "📊 CHECK IMAGE SIZE:"
echo "   docker images mathia-web"
echo ""
echo "⏱️  TIME A BUILD:"
echo "   time docker-compose build"
echo ""
