"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from decimal import Decimal
import os
import sys
from pathlib import Path
import dj_database_url
from celery.schedules import crontab
# load environment variables from project .env
try:
    from dotenv import load_dotenv
    # .env is located one level above the Backend folder (project root)
    # BASE_DIR is defined below so load using file path after BASE_DIR or use parent placeholder
except Exception:
    def load_dotenv(*args, **kwargs):
        return None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR.parent / '.env'
load_dotenv(dotenv_path=env_path, override=True)

# attempt to load .env from project root (one level above BASE_DIR)
try:
    load_dotenv(str(BASE_DIR.parent / '.env'))
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

def _load_or_create_dev_secret_key(key_file):
    # Stable per-checkout dev key stored in a gitignored file so sessions
    # survive across gunicorn workers and restarts. Returns (key, persisted).
    # Silent by design: callers must never log the key itself.
    try:
        key = key_file.read_text().strip()
    except OSError:
        key = ''
    if key:
        return key, True
    import secrets
    key = secrets.token_urlsafe(50)
    try:
        key_file.write_text(key)
        return key, True
    except OSError:
        return key, False


# SECURITY WARNING: keep the secret key used in production secret!
# CRITICAL: SECRET_KEY must be set via environment variable in production
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes'):
        SECRET_KEY, _key_persisted = _load_or_create_dev_secret_key(
            Path(os.environ.get('DJANGO_DEV_SECRET_KEY_FILE') or (BASE_DIR.parent / '.dev_secret_key'))
        )
        if _key_persisted:
            print("⚠️  DEV ONLY: SECRET_KEY served from the gitignored .dev_secret_key fallback. Set DJANGO_SECRET_KEY in .env.")
        else:
            print("⚠️  DEV ONLY: auto-generated SECRET_KEY could not be persisted; sessions reset between processes. Set DJANGO_SECRET_KEY in .env.")
    else:
        raise ValueError(
            "CRITICAL SECURITY ERROR: DJANGO_SECRET_KEY environment variable must be set in production. "
            "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes')

# --- Dev fallback: no Redis/Postgres (e.g. Docker unavailable) ---------------
# When DEBUG is on and Redis is unreachable at boot, run fully in-memory and on
# SQLite so `manage.py runserver` works natively from a venv. Production
# (DEBUG=False) never falls back. Force with KAZI_DEV_INMEMORY=1.
import socket as _socket
from urllib.parse import urlparse as _urlparse


def _redis_reachable(url: str) -> bool:
    try:
        parsed = _urlparse(str(url))
        host, port = parsed.hostname, (parsed.port or 6379)
    except Exception:
        return False
    if not host:
        return False
    try:
        with _socket.create_connection((host, port), timeout=0.5):
            return True
    except OSError:
        return False


_DEV_INMEMORY = DEBUG and os.environ.get('KAZI_DEV_INMEMORY', '').lower() in ('1', 'true', 'yes', 'on')
if not _DEV_INMEMORY:
    # Auto-fall back only when the config expects the Docker network (its DB
    # host is a compose service) and Redis is unreachable. CI/hermetic runs with
    # no DATABASE_URL keep the normal settings.
    _db_host = _urlparse(os.environ.get('DATABASE_URL', '')).hostname or ""
    if DEBUG and _db_host in {'db', 'postgres', 'postgresql'}:
        _DEV_INMEMORY = not _redis_reachable(os.environ.get('REDIS_URL', 'redis://redis:6379/0'))

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]

# CSRF & CORS configuration - be explicit and restrictive
# you can set a comma-separated list in .env, e.g. DJANGO_CSRF_TRUSTED_ORIGINS=https://example.com,https://app.example.com
CSRF_TRUSTED_ORIGINS_STRING = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if not CSRF_TRUSTED_ORIGINS_STRING and not DEBUG:
    raise ValueError(
        "SECURITY WARNING: DJANGO_CSRF_TRUSTED_ORIGINS must be explicitly set in production. "
        "Set it in .env as a comma-separated list of allowed origins (e.g., https://example.com)"
    )
CSRF_TRUSTED_ORIGINS = [url.strip() for url in CSRF_TRUSTED_ORIGINS_STRING.split(',') if url.strip()] if CSRF_TRUSTED_ORIGINS_STRING else []

# Additional CSRF security
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Calendly app credentials (set in .env)
CALENDLY_CLIENT_ID = os.environ.get('CALENDLY_CLIENT_ID')
CALENDLY_CLIENT_SECRET = os.environ.get('CALENDLY_CLIENT_SECRET')
CALENDLY_WEBHOOK_SIGNING_KEY = (
    os.environ.get('CALENDLY_WEBHOOK_SIGNING_KEY')
    or os.environ.get('Webhook_signing_key')
)

# IntaSend webhook secret for signature verification
INTASEND_WEBHOOK_SECRET = os.environ.get('INTASEND_WEBHOOK_SECRET')

# Governed shell sidecar (v0.6, #130). The sidecar runs one command in a
# sandboxed container; Kazi never touches Docker or a raw shell itself.
# Leaving SHELL_EXEC_TOKEN blank disables run_command entirely (fail closed).
SHELL_EXEC_HOST = os.environ.get('SHELL_EXEC_HOST', '127.0.0.1')
SHELL_EXEC_PORT = int(os.environ.get('SHELL_EXEC_PORT', '8765'))
SHELL_EXEC_TOKEN = os.environ.get('SHELL_EXEC_TOKEN', '')
SHELL_EXEC_PROFILE = os.environ.get('SHELL_EXEC_PROFILE', 'standard')
# Profiles the sidecar will serve. Empty = the single SHELL_EXEC_PROFILE (or
# "standard"). Add "open" only on a disposable box — it runs unsandboxed.
SHELL_EXEC_PROFILES = [
    profile.strip()
    for profile in os.environ.get('SHELL_EXEC_PROFILES', '').split(',')
    if profile.strip()
]
SHELL_EXEC_ROOT = os.environ.get('SHELL_EXEC_ROOT', '')
SHELL_EXEC_IMAGE = os.environ.get('SHELL_EXEC_IMAGE', 'alpine:3.20')
SHELL_EXEC_USER = os.environ.get('SHELL_EXEC_USER', '65534:65534')
SHELL_EXEC_MEMORY = os.environ.get('SHELL_EXEC_MEMORY', '256m')
SHELL_EXEC_PIDS_LIMIT = int(os.environ.get('SHELL_EXEC_PIDS_LIMIT', '128'))
SHELL_EXEC_TIMEOUT_DEFAULT = int(os.environ.get('SHELL_EXEC_TIMEOUT_DEFAULT', '120'))
SHELL_EXEC_TIMEOUT_MAX = int(os.environ.get('SHELL_EXEC_TIMEOUT_MAX', '600'))
SHELL_EXEC_OUTPUT_BYTES_MAX = int(os.environ.get('SHELL_EXEC_OUTPUT_BYTES_MAX', '65536'))
SHELL_EXEC_NETWORK_ALLOWLIST = [
    host.strip()
    for host in os.environ.get('SHELL_EXEC_NETWORK_ALLOWLIST', '').split(',')
    if host.strip()
]
# Enforced egress for the `standard` profile: a stock Squid proxy is the only
# way out of the sandbox. Off until verified on your Docker host
# (scripts/verify_shell_egress.py).
SHELL_EGRESS_PROXY = os.environ.get('SHELL_EGRESS_PROXY', 'False').lower() in ('1', 'true', 'yes')
SHELL_EGRESS_PROXY_IMAGE = os.environ.get('SHELL_EGRESS_PROXY_IMAGE', 'kazi-egress-squid:1')
# Unset = the built-in registry list (orchestration/shell/egress.py). Set it,
# even to an empty value, to replace that list.
_egress_default_hosts = os.environ.get('SHELL_EGRESS_DEFAULT_HOSTS')
SHELL_EGRESS_DEFAULT_HOSTS = None if _egress_default_hosts is None else [
    host.strip() for host in _egress_default_hosts.split(',') if host.strip()
]
SHELL_HOST_GRANT_DAYS = int(os.environ.get('SHELL_HOST_GRANT_DAYS', '30'))
SHELL_HOST_GRANT_MAX_DAYS = int(os.environ.get('SHELL_HOST_GRANT_MAX_DAYS', '365'))
# Who may approve a new host for a room: `members` (any member) or `staff`.
SHELL_HOST_GRANT_APPROVERS = os.environ.get('SHELL_HOST_GRANT_APPROVERS', 'members')
# Human-armed autopilot window for the unsandboxed `open` shell profile.
SHELL_AUTOPILOT_MINUTES = int(os.environ.get('SHELL_AUTOPILOT_MINUTES', '30'))
SHELL_AUTOPILOT_MAX_MINUTES = int(os.environ.get('SHELL_AUTOPILOT_MAX_MINUTES', '120'))
# How long a room stays tainted after untrusted text enters it (0 = this run only).
AGENT_TAINT_TTL_SECONDS = int(os.environ.get('AGENT_TAINT_TTL_SECONDS', '900'))

# Eval scenario packs (#171): each capability pack in the golden harness must
# ship at least this many scenarios. Guarded by test_scenario_packs.
SCENARIO_PACK_MIN_SIZE = int(os.environ.get('SCENARIO_PACK_MIN_SIZE', '3'))

# Preference mining (#152): mine approve/deny history into learned overrides.
PREFERENCE_MINING_ENABLED = os.environ.get('PREFERENCE_MINING_ENABLED', 'True').lower() in ('1', 'true', 'yes')
PREFERENCE_MINING_MIN_APPROVALS = int(os.environ.get('PREFERENCE_MINING_MIN_APPROVALS', '3'))
PREFERENCE_MINING_WINDOW_DAYS = int(os.environ.get('PREFERENCE_MINING_WINDOW_DAYS', '30'))

# Initiative ladder (#154): proactive actions per user per day (hard cap).
PROACTIVE_BUDGET_PER_DAY = int(os.environ.get('PROACTIVE_BUDGET_PER_DAY', '2'))

# Application definition

INSTALLED_APPS = [
    'daphne',
    # Admin UI Enhancement (must be before django.contrib.admin)
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'chatbot',
    'users',
    'Api',
    'orchestration',
    'travel',
    'payments',
    'workflows',
    'notifications',
    'tests',
    'rest_framework',
    'rest_framework.authtoken',
    'django_celery_beat',
    'django_celery_results',

    # Sites (required by allauth)
    'django.contrib.sites',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'allauth.socialaccount.providers.twitter',

    # Import/Export
    'import_export',

    # Security
    'axes',
    'django_ratelimit',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.TrialExpiryMiddleware',
    'chatbot.middleware.EnsureMemberMiddleware',  # Auto-create Member objects
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Security Middleware
    'axes.middleware.AxesMiddleware',  # Brute force protection
    'csp.middleware.CSPMiddleware',   # Content Security Policy

    # Allauth Account Middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.shell_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'

ASGI_APPLICATION = "Backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

_DATABASE_URL = os.environ.get('DATABASE_URL', 'sqlite:///' + str(BASE_DIR / 'db.sqlite3'))
if _DEV_INMEMORY and _urlparse(_DATABASE_URL).hostname in {'db', 'postgres', 'postgresql'}:
    # The configured Postgres lives on the Docker network; fall back to SQLite.
    _DATABASE_URL = 'sqlite:///' + str(BASE_DIR / 'db.sqlite3')

DATABASES = {
    'default': dj_database_url.parse(
        _DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
}

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Redis configuration for Celery, Caching, and Channels
# Read Redis URL from environment so containers use the Compose service hostname
REDIS_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
if _DEV_INMEMORY:
    # No broker; run tasks inline in the web process.
    CELERY_BROKER_URL = 'memory://'
CELERY_TASK_ALWAYS_EAGER = _DEV_INMEMORY

# Temporal configuration for workflow execution
TEMPORAL_HOST = os.environ.get('TEMPORAL_HOST', 'localhost:7233')
TEMPORAL_NAMESPACE = os.environ.get('TEMPORAL_NAMESPACE', 'default')
TEMPORAL_TASK_QUEUE = os.environ.get('TEMPORAL_TASK_QUEUE', 'user-workflows')
TEMPORAL_DISABLED = os.environ.get('TEMPORAL_DISABLED', 'False').lower() in ('1', 'true', 'yes')
# Approval decisions go through the Workflow Update API (typed request/response
# per approval id) instead of fire-and-forget signals. Default off — reversible.
WORKFLOW_APPROVALS_UPDATE_API = os.environ.get('WORKFLOW_APPROVALS_UPDATE_API', 'False').lower() in ('1', 'true', 'yes')

# Workflow safety limits
WORKFLOW_WITHDRAW_MAX = Decimal(os.environ.get('WORKFLOW_WITHDRAW_MAX', '10000'))

# Travel connectors: allow mock fallbacks in dev only
TRAVEL_ALLOW_FALLBACK = os.environ.get('TRAVEL_ALLOW_FALLBACK', str(DEBUG)).lower() in ('1', 'true', 'yes')

# Celery Results — env-overridable so deployments can switch backends
# (e.g. redis://) without code changes; django-db remains the default.
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'django-db')
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_TASK_IGNORE_RESULT = os.environ.get('CELERY_TASK_IGNORE_RESULT', 'True').lower() in ('1', 'true', 'yes')

# Celery serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery execution
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
CELERY_WORKER_CONCURRENCY = int(os.environ.get('CELERY_CONCURRENCY', 1))
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(os.environ.get('CELERY_WORKER_MAX_TASKS_PER_CHILD', 200))
CELERY_WORKER_MAX_MEMORY_PER_CHILD = int(os.environ.get('CELERY_WORKER_MAX_MEMORY_PER_CHILD', 250000))  # KiB
CELERY_RESULT_EXPIRES = int(os.environ.get('CELERY_RESULT_EXPIRES', 3600))  # 1 hour

# Django Cache with local Redis
# IGNORE_EXCEPTIONS: when Redis is down, HTTP views must still serve —
# cache reads return the default and writes are skipped (logged) instead of 500ing.
REDIS_CACHE_IGNORE_EXCEPTIONS = os.environ.get('REDIS_CACHE_IGNORE_EXCEPTIONS', '1').lower() in ('1', 'true', 'yes')
if _DEV_INMEMORY:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "kazi-dev-inmemory",
        }
    }
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
    }
    # LocMem is not a shared cache; ratelimit's check is a hard error otherwise.
    SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": REDIS_CACHE_IGNORE_EXCEPTIONS,
            }
        }
    }
    DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True

    # Channels Layer with local Redis
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    {
                        "address": REDIS_URL,
                        # redis-py 8.0.0 defaults socket_timeout to 5s, which
                        # collides with channels_redis's 5s bzpopmin poll and
                        # tears down otherwise-idle WebSockets. None restores the
                        # pre-8.0 behaviour; bzpopmin still returns on its own
                        # 5s poll without raising.
                        "socket_timeout": None,
                    }
                ],
            },
        },
    }

# Celery Beat Schedule — single source of truth. A second definition later in
# this file silently replaced this dict once already (dropping the reminder
# sweep and the deferred-workflow replay watchdog); never redefine it below.
MODERATION_ENABLED = os.environ.get('MODERATION_ENABLED')
if MODERATION_ENABLED is None:
    MODERATION_ENABLED = bool(os.environ.get('HF_API_TOKEN', ''))
else:
    MODERATION_ENABLED = MODERATION_ENABLED.lower() in ('1', 'true', 'yes')

MODERATION_FLUSH_SECONDS = int(os.environ.get('MODERATION_FLUSH_SECONDS', 600))
REMINDER_SWEEP_SECONDS = int(os.environ.get('REMINDER_SWEEP_SECONDS', 3600))
WORKFLOW_REPLAY_SCHEDULE_SECONDS = int(os.environ.get('WORKFLOW_REPLAY_SCHEDULE_SECONDS', 300))
WORKFLOW_APPROVAL_SWEEP_SECONDS = int(os.environ.get('WORKFLOW_APPROVAL_SWEEP_SECONDS', 300))
PROMOTION_MIN_OCCURRENCES = int(os.environ.get('PROMOTION_MIN_OCCURRENCES', 3))
PROMOTION_MIN_SUCCESS_RATE = float(os.environ.get('PROMOTION_MIN_SUCCESS_RATE', 0.8))
ROUTINE_ABSENCE_IDLE_DAYS = int(os.environ.get('ROUTINE_ABSENCE_IDLE_DAYS', 14))
ROUTINE_ABSENCE_PROMPT_WINDOW_DAYS = int(os.environ.get('ROUTINE_ABSENCE_PROMPT_WINDOW_DAYS', 3))
ROUTINE_HISTORY_LIMIT = int(os.environ.get('ROUTINE_HISTORY_LIMIT', 20))
SKILL_STALE_AFTER_DAYS = int(os.environ.get('SKILL_STALE_AFTER_DAYS', 90))
SKILL_ARCHIVE_AFTER_DAYS = int(os.environ.get('SKILL_ARCHIVE_AFTER_DAYS', 180))
STANDING_GRANT_LIFETIME_DAYS = int(os.environ.get('STANDING_GRANT_LIFETIME_DAYS', 30))
APPROVAL_TELEMETRY_WINDOW_DAYS = int(os.environ.get('APPROVAL_TELEMETRY_WINDOW_DAYS', 1))
APPROVAL_PROMOTE_THRESHOLD_RATE = float(os.environ.get('APPROVAL_PROMOTE_THRESHOLD_RATE', 0.95))
APPROVAL_PROMOTE_THRESHOLD_COUNT = int(os.environ.get('APPROVAL_PROMOTE_THRESHOLD_COUNT', 50))
WORKFLOW_HEALTH_WINDOW_HOURS = int(os.environ.get('WORKFLOW_HEALTH_WINDOW_HOURS', 24))
WORKFLOW_HEALTH_FAILURE_SPIKE = int(os.environ.get('WORKFLOW_HEALTH_FAILURE_SPIKE', 3))
WORKFLOW_HEALTH_DEGRADED_RATE = float(os.environ.get('WORKFLOW_HEALTH_DEGRADED_RATE', 0.3))
SHADOW_REPLAY_WINDOW = int(os.environ.get('SHADOW_REPLAY_WINDOW', 10))
WORKFLOW_REVIEWER_WINDOW_DAYS = int(os.environ.get('WORKFLOW_REVIEWER_WINDOW_DAYS', 30))
WORKFLOW_REVIEWER_ENABLED = os.environ.get('WORKFLOW_REVIEWER_ENABLED', 'true').lower() in ('1', 'true', 'yes')
HANDOFF_DEFAULT_BUDGET = int(os.environ.get('HANDOFF_DEFAULT_BUDGET', 20))
HANDOFF_MAX_BUDGET = int(os.environ.get('HANDOFF_MAX_BUDGET', 50))

CELERY_BEAT_SCHEDULE = {
    'nightly_ledger_reconciliation': {
        'task': 'payments.tasks.reconcile_ledger',
        'schedule': crontab(hour=2, minute=0),
    },
    'daily_recurring_invoices': {
        'task': 'payments.tasks.process_recurring_invoices',
        'schedule': crontab(hour=1, minute=0),
    },
    'sweep-memory-notes': {
        'task': 'chatbot.tasks.sweep_memory_notes',
        'schedule': 21600.0,  # Every 6 hours
    },
    'check-due-reminders': {
        'task': 'chatbot.tasks.check_due_reminders',
        'schedule': float(REMINDER_SWEEP_SECONDS),  # Safety sweep
    },
    'send-trial-summary': {
        'task': 'users.tasks.send_trial_summary_task',
        'schedule': crontab(hour=7, minute=0),  # every day at 07:00
    },
    'sweep-stuck-approvals': {
        'task': 'workflows.tasks.sweep_stuck_approvals',
        'schedule': float(WORKFLOW_APPROVAL_SWEEP_SECONDS),
    },
    'roll-telemetry': {
        'task': 'orchestration.tasks.roll_telemetry',
        'schedule': crontab(hour=3, minute=0),  # Nightly: rotate + roll up JSONL telemetry
    },
    'mine-approval-preferences': {
        'task': 'orchestration.tasks.mine_approval_preferences',
        'schedule': crontab(hour=3, minute=30),  # Nightly: mine approve/deny -> learned overrides
    },
    'send-daily-digest': {
        'task': 'orchestration.tasks.send_daily_digest',
        'schedule': crontab(hour=7, minute=30),  # Morning: initiative rung-2 digest
    },
    'mine-workflow-candidates': {
        'task': 'workflows.tasks.mine_workflow_candidates',
        'schedule': crontab(hour=4, minute=0),  # Nightly: repeated tool sequences -> skill candidates
    },
    'check-routine-absence': {
        'task': 'workflows.tasks.check_routine_absence',
        'schedule': crontab(hour=5, minute=0),  # Daily: idle owners -> keep-running prompt -> pause
    },
    'curate-skill-lifecycle': {
        'task': 'orchestration.tasks.curate_skill_lifecycle',
        'schedule': crontab(day_of_week=1, hour=4, minute=30),  # Weekly: demote unused skills
    },
    'sweep-expired-grants': {
        'task': 'workflows.tasks.sweep_expired_grants',
        'schedule': crontab(hour=3, minute=45),  # Nightly: lapse standing grants past expiry
    },
    'roll-approval-telemetry': {
        'task': 'orchestration.tasks.roll_approval_telemetry',
        'schedule': crontab(hour=3, minute=15),  # Nightly: approve/reject metrics + rule candidates
    },
    'check-workflow-health': {
        'task': 'workflows.tasks.check_workflow_health',
        'schedule': crontab(minute=0),  # Hourly: failure spikes -> auto-pause
    },
    'check-schedule-health': {
        'task': 'workflows.tasks.check_schedule_health',
        'schedule': crontab(minute=5),  # Hourly: skipped schedule fires -> alert
    },
    'send-workflow-health-digest': {
        'task': 'workflows.tasks.send_workflow_health_digest',
        'schedule': crontab(day_of_week=1, hour=8, minute=0),  # Weekly: healthy/degraded/paused
    },
    'run-workflow-reviewer': {
        'task': 'workflows.tasks.run_workflow_reviewer',
        'schedule': crontab(day_of_week=1, hour=2, minute=0),  # Weekly: metric-citing suggestions
    },
}

if MODERATION_ENABLED:
    CELERY_BEAT_SCHEDULE.update({
        'flush-moderation-batches': {
            'task': 'chatbot.tasks.process_pending_batches',
            'schedule': float(MODERATION_FLUSH_SECONDS),  # Batch moderation
        },
        'cleanup-old-batches': {
            'task': 'chatbot.tasks.cleanup_old_moderation_batches',
            'schedule': 86400.0,  # Daily
        },
    })

if not TEMPORAL_DISABLED:
    CELERY_BEAT_SCHEDULE.update({
        'replay-deferred-workflows': {
            'task': 'workflows.tasks.replay_deferred_workflows',
            'schedule': float(WORKFLOW_REPLAY_SCHEDULE_SECONDS),  # Batch replays
        },
    })

# Beat runs off the DB scheduler so runtime edits survive deploys and the
# settings-dict clobber class of bug (#73) is structurally dead. The dict above
# stays the source of truth: `manage.py sync_beat_schedule` mirrors it into the
# database (and disables entries that are no longer declared here).
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# AI Moderation Settings
MODERATION_BATCH_SIZE = 10
MODERATION_BATCH_TIMEOUT = 5
MODERATION_FLAG_THRESHOLD = 3
HF_API_TOKEN = os.environ.get('HF_API_TOKEN', '')
HF_MONTHLY_LIMIT = 10000  # e.g., 10,000 tokens per month

# External API Keys for Connectors
OPENWEATHER_API_KEY = os.environ.get('OPENWEATHER_API_KEY', '')
GIPHY_API_KEY = os.environ.get('GIPHY_API_KEY', '')
EXCHANGE_RATE_API_KEY = os.environ.get('EXCHANGE_RATE_API_KEY', '')
GMAIL_OAUTH_CLIENT_ID = os.environ.get('GMAIL_OAUTH_CLIENT_ID') or os.environ.get('GOOGLE_CLIENT_ID')
GMAIL_OAUTH_CLIENT_SECRET = os.environ.get('GMAIL_OAUTH_CLIENT_SECRET') or os.environ.get('GOOGLE_CLIENT_SECRET')
GMAIL_OAUTH_REDIRECT_URI = os.environ.get('GMAIL_OAUTH_REDIRECT_URI', '')
GMAIL_SEND_SCOPE = 'https://www.googleapis.com/auth/gmail.send'

# Messaging connectors
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')

# Kazi platform
KAZI_AGENT_NAME = os.environ.get('KAZI_AGENT_NAME', 'Kazi')

# LLM providers (Anthropic first, DeepSeek + Hugging Face fallbacks)
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')
DEEPSEEK_MODEL = os.environ.get('DEEPSEEK_MODEL', 'deepseek-chat')
DEEPSEEK_BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com/v1/chat/completions')
LLM_PLANNER_PROVIDER = os.environ.get('LLM_PLANNER_PROVIDER', 'anthropic')
LLM_EXECUTOR_PROVIDER = os.environ.get('LLM_EXECUTOR_PROVIDER', 'huggingface')
LLM_PLANNER_MODEL = os.environ.get('LLM_PLANNER_MODEL', '')
LLM_EXECUTOR_MODEL = os.environ.get('LLM_EXECUTOR_MODEL', '')

# LLM token quota
LLM_TOKEN_QUOTA_ENABLED = os.environ.get('LLM_TOKEN_QUOTA_ENABLED', 'True').lower() in ('1', 'true', 'yes')
LLM_TOKEN_LIMIT_PER_USER_PER_HOUR = int(os.environ.get('LLM_TOKEN_LIMIT_PER_USER_PER_HOUR', 50000))

# LLM cost guards
LLM_MAX_TOKENS = int(os.environ.get('LLM_MAX_TOKENS', 700))  # hard ceiling per call
LLM_PROMPT_CHAR_LIMIT = int(os.environ.get('LLM_PROMPT_CHAR_LIMIT', 4000))  # truncate user prompt to this many chars
CONTEXT_PROMPT_MAX_CHARS = int(os.environ.get('CONTEXT_PROMPT_MAX_CHARS', 8000))  # cap room context injected into the system prompt
SKILL_MAX_CHARS = int(os.environ.get('SKILL_MAX_CHARS', 8000))  # cap a loaded skill's instruction body
HISTORY_MAX_CHARS = int(os.environ.get('HISTORY_MAX_CHARS', 60000))  # conversation history budget before auto-compaction
HISTORY_MAX_MESSAGES = int(os.environ.get('HISTORY_MAX_MESSAGES', 50))  # max history turns kept in an agent loop
HISTORY_COMPACTION_ENABLED = os.environ.get('HISTORY_COMPACTION_ENABLED', 'True').lower() in ('1', 'true', 'yes')  # trim oldest turns when history exceeds the budget
LLM_CACHE_ENABLED = os.environ.get('LLM_CACHE_ENABLED', 'True').lower() in ('1', 'true', 'yes')
LLM_CACHE_TTL_SECONDS = int(os.environ.get('LLM_CACHE_TTL_SECONDS', 600))
LLM_CACHE_MIN_TEMP = float(os.environ.get('LLM_CACHE_MIN_TEMP', 0.3))

# Manager agent LLM fallback
MANAGER_LLM_ENABLED = os.environ.get('MANAGER_LLM_ENABLED', 'True').lower() in ('1', 'true', 'yes')

# Orchestration startup integrity checks (connector <-> action catalog).
# Previously only checked via getattr(settings, ..., True) which could never be
# disabled. Wired to env so CI/dev can skip the eager MCPRouter construction.
ORCHESTRATION_STRICT_STARTUP_CHECKS = os.environ.get('ORCHESTRATION_STRICT_STARTUP_CHECKS', 'True').lower() in ('1', 'true', 'yes')

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {'user_attributes': ['email', 'username', 'first_name', 'last_name']}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12}  # Increased from default 8 for better security
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Session security
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
# Lax to allow WS/session cookies after redirects in dev; keep secure via HTTPS in prod
SESSION_COOKIE_SAMESITE = 'Lax'

MEDIA_URL = '/uploads/'  # Base URL for media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')  # Directory to store uploaded files

R2_ENABLED = os.environ.get('R2_ENABLED', 'False').lower() in ('1', 'true', 'yes')
if R2_ENABLED:
    AWS_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('R2_ENDPOINT_URL')
    AWS_S3_REGION_NAME = os.environ.get('R2_REGION', 'auto')
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

    if not AWS_ACCESS_KEY_ID or not AWS_SECRET_ACCESS_KEY or not AWS_STORAGE_BUCKET_NAME or not AWS_S3_ENDPOINT_URL:
        raise ValueError('R2 is enabled but required R2_* settings are missing.')

    AWS_S3_CUSTOM_DOMAIN = os.environ.get('R2_PUBLIC_BASE_URL', '')
    if AWS_S3_CUSTOM_DOMAIN:
        AWS_S3_CUSTOM_DOMAIN = AWS_S3_CUSTOM_DOMAIN.replace('https://', '').replace('http://', '')
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    else:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'chatbot/static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGIN_REDIRECT_URL = 'users:dashboard'
LOGIN_URL = 'users:login'
LOGOUT_REDIRECT_URL = 'users:login'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",

    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly"
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 5,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "Api.throttling.GlobalApiThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/minute",
        "global_api": "60/minute",  # Default fallback, overridden by class logic
        "ai_request": "10/day"      # Default fallback
    }
}


# Chat rate limit (messages per minute)
CHAT_RATE_LIMIT = 30

# ==========================================
# AUTHENTICATION & SECURITY CONFIGURATION
# ==========================================

# ==========================================
# AUTHENTICATION & SECURITY CONFIGURATION
# ==========================================

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# --- Allauth Settings (Latest Format) ---
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_SESSION_REMEMBER = True
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_ADAPTER = 'users.social_adapter.InviteGatedSocialAdapter'

# Social Providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', 'dummy_google_client_id'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', 'dummy_google_secret'),
        }
    },
    'github': {
        'SCOPE': ['user', 'read:org'],
        'APP': {
            'client_id': os.environ.get('GITHUB_CLIENT_ID', 'dummy_github_client_id'),
            'secret': os.environ.get('GITHUB_CLIENT_SECRET', 'dummy_github_secret'),
        }
    },
    'linkedin_oauth2': {
        'SCOPE': ['r_liteprofile', 'r_emailaddress'],
        'APP': {
            'client_id': os.environ.get('LINKEDIN_CLIENT_ID', 'dummy_linkedin_id'),
            'secret': os.environ.get('LINKEDIN_CLIENT_SECRET', 'dummy_linkedin_secret'),
        }
    },
    'twitter': {
        'APP': {
            'client_id': os.environ.get('TWITTER_CLIENT_ID', 'dummy_twitter_id'),
            'secret': os.environ.get('TWITTER_CLIENT_SECRET', 'dummy_twitter_secret'),
        }
    }
}


# --- AXES (Brute Force Protection) - Enhanced Security ---
from datetime import timedelta

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=2)
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_RESET_ON_SUCCESS = True
AXES_VERBOSE = True
AXES_ENABLE_ADMIN = True


# --- CSP (Content Security Policy) ---
# --- CSP (Content Security Policy) ---
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdnjs.cloudflare.com", "https://cdn.jsdelivr.net")
CSP_SCRIPT_SRC = ("'self'", "https://js.stripe.com", "https://cdn.tailwindcss.com", "https://cdn.jsdelivr.net", "https://assets.calendly.com", "https://code.jquery.com", "https://cdnjs.cloudflare.com")
CSP_IMG_SRC = ("'self'", "data:", "https://*")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://cdnjs.cloudflare.com")
CSP_FRAME_SRC = ("'self'", "https://js.stripe.com")

# --- HSTS (HTTP Strict Transport Security) ---
# Enabled only when DEBUG is False to avoid local dev issues
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_HTTPONLY = True
    # Keep CSRF cookie readable for JS fetch headers (pin notes, add notes)
    CSRF_COOKIE_HTTPONLY = False
    SECURE_CONTENT_TYPE_NOSNIFF = True


# ==========================================
# DJANGO-JAZZMIN ADMIN CONFIGURATION
# ==========================================

JAZZMIN_SETTINGS = {
    "site_header": "Kazi Admin",
    "site_title": "Kazi Administration",
    "welcome_sign": "Welcome to Kazi Administration",
    "copyright": "Kazi Platform",

    # Dashboard and display settings
    "show_ui_builder": False,
    "use_google_fonts_cdn": True,

    # Theme configuration
    "theme": "default",  # Can be 'default', 'dark' or custom
    "dark_mode_theme": "darkly",

    # Colors
    "user_avatar": None,

    # Pagination
    "pagination_per_page": 20,

    # Admin site branding
    "site_icon": None,  # Optional: add path to icon image
    "has_search": True,
    "search_model": "auth.User",

    # Navigation
    "show_sidebar": True,
    "navigation_expanded": False,

    # Search settings
    "search_allow_url_search": True,

    # Custom links in sidebar
    "navigation": [
        {"app": "users", "icon": "fas fa-users"},
        {"app": "payments", "icon": "fas fa-credit-card"},
        {"app": "travel", "icon": "fas fa-plane"},
        {"app": "chatbot", "icon": "fas fa-comments"},
        {"app": "workflows", "icon": "fas fa-project-diagram"},
        {"app": "orchestration", "icon": "fas fa-cogs"},
        {"app": "auth", "icon": "fas fa-lock"},
    ],
}

# Jazzmin UI tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "tooltip_class": "tooltip-primary",
    "window_box_shadow_class": "card-shadow",
}

TEST_RUNNER = 'tests.runner.KaziDiscoverRunner'

if 'test' in sys.argv:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "kazi-tests",
        }
    }
    SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003']
