# Generated by Django 5.2.9 on 2025-12-28 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('location_country', models.CharField(max_length=100)),
                ('ticket_price_ksh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ticket_url', models.URLField(blank=True, null=True)),
                ('provider', models.CharField(max_length=100)),
                ('provider_id', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['location_country', 'start_datetime'], name='travel_even_locatio_aaa813_idx'), models.Index(fields=['category'], name='travel_even_categor_052ef8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(choices=[('kenya', 'Kenya'), ('east_africa', 'East Africa'), ('africa', 'Africa'), ('worldwide', 'Worldwide')], default='kenya', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget_ksh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_itineraries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('bus', 'Bus Ticket'), ('hotel', 'Hotel'), ('flight', 'Flight'), ('transfer', 'Transfer'), ('event', 'Event'), ('activity', 'Activity'), ('restaurant', 'Restaurant'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price_ksh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_currency', models.CharField(default='KES', max_length=3)),
                ('booking_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.itinerary')),
            ],
            options={
                'ordering': ['itinerary', 'sort_order', 'start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BookingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('provider_booking_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booking_url', models.URLField()),
                ('confirmation_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('itinerary_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_reference', to='travel.itineraryitem')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(choices=[('buupass', 'Buupass'), ('booking', 'Booking.com'), ('duffel', 'Duffel'), ('karibu', 'Karibu Taxi'), ('eventbrite', 'Eventbrite')], max_length=50)),
                ('query_json', models.JSONField()),
                ('result_json', models.JSONField()),
                ('ttl_seconds', models.IntegerField(default=3600)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('hit_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='travel_sear_expires_3408d8_idx'), models.Index(fields=['provider', 'created_at'], name='travel_sear_provide_abd7eb_idx')],
                'unique_together': {('query_hash', 'provider')},
            },
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['user', '-created_at'], name='travel_itin_user_id_11c7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['status'], name='travel_itin_status_9063dc_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['itinerary', 'start_datetime'], name='travel_itin_itinera_ed3c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['status'], name='travel_itin_status_d427c7_idx'),
        ),
    ]
