"""Configuration for the stock Squid proxy that bounds sandbox egress.

Kazi does not implement a proxy (posted guidance on #134: "Do not hand-write an
egress proxy. Use a stock, widely used one."). This module only renders text
for Squid and reads its access log. Everything here is a pure function so it
can be tested without Docker. See ``docs/plans/2026-10-shell-egress-proxy.md``.

One Squid runs per sandboxed command, on that command's own internal network,
so its allowlist is exactly that room's approved hosts and no authentication
is needed: nothing else can reach it.
"""
from __future__ import annotations

import re
from typing import Iterable, List, Tuple

PROXY_ALIAS = "proxy"
CONFIG_PATH = "/etc/squid/kazi.conf"
HOSTS_PATH = "/etc/squid/kazi-hosts.txt"
LOG_DIR = "/var/log/kazi"
READY_MARKER = "Accepting"

# A public DNS name with an alphabetic top-level label, optionally with a
# leading dot (Squid's "this domain and its subdomains"). No IP literals and
# no numeric look-alikes (``127.1``, ``0x7f.1``): those are not names a human
# approved.
_HOST_ENTRY = re.compile(
    r"^\.?(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z][a-z0-9-]{0,61}[a-z0-9]$"
)

# Destinations no approved name may resolve to: loopback, private, link-local
# (cloud metadata), carrier NAT, multicast/reserved, and their IPv6 kin.
# Do NOT add ::ffff:0:0/96 here: Squid stores every IPv4 address as IPv4-mapped
# IPv6, so that range means "all of IPv4" and would refuse everything (seen on
# a real daemon, 2026-10-04). The IPv4 ranges already cover mapped addresses.
_PRIVATE_RANGES = (
    "0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 "
    "192.0.0.0/24 192.168.0.0/16 198.18.0.0/15 224.0.0.0/3 "
    "::/128 ::1/128 64:ff9b::/96 fc00::/7 fe80::/10 ff00::/8"
)

_CONFIG = """\
# Generated by Kazi for ONE sandboxed command. Do not edit.
# Stock Squid: HTTPS tunnels to approved domains only. Nothing is decrypted.
http_port {port} ssl-bump tls-cert=/etc/squid/kazi-dummy.pem
pid_filename none
pinger_enable off
cache deny all
cache_log {log_dir}/cache.log
logformat kazi %Ss %rm %ru %ssl::>sni
access_log stdio:{log_dir}/access.log kazi
coredump_dir /tmp
shutdown_lifetime 1 seconds
via off
forwarded_for delete
sslcrtd_program /usr/lib/squid/security_file_certgen -s /var/lib/kazi-ssl_db -M 4MB
sslcrtd_children 1 startup=1 idle=1

acl kazi_hosts dstdomain "{hosts_path}"
acl kazi_sni ssl::server_name --client-requested "{hosts_path}"
acl kazi_connect method CONNECT
acl kazi_tls port 443
# A raw IP target would be matched against the allowlist by reverse DNS,
# which the address owner controls. Refuse IP literals outright.
acl kazi_ip_literal url_regex ^[0-9.]+: ^\\[
acl kazi_private dst {private}
acl kazi_step1 at_step SslBump1

http_access deny !kazi_connect
http_access deny !kazi_tls
http_access deny kazi_ip_literal
http_access deny !kazi_hosts
http_access deny kazi_private
http_access allow kazi_connect kazi_tls kazi_hosts
http_access deny all
# Refuse by resetting the connection. Without this Squid answers "200", then
# serves its error page under the unused certificate, which reads to a client
# like a TLS problem rather than a refusal. (A private-address refusal still
# takes that path; either way nothing is tunnelled.)
deny_info TCP_RESET kazi_connect
deny_info TCP_RESET kazi_tls
deny_info TCP_RESET kazi_ip_literal
deny_info TCP_RESET kazi_hosts
deny_info TCP_RESET kazi_private
deny_info TCP_RESET all

# Read only the TLS ClientHello: the name the client asks for (SNI) must also
# be an approved host, so an approved name cannot front for another site on
# the same CDN. Then tunnel without decrypting, or drop.
ssl_bump peek kazi_step1
ssl_bump splice kazi_sni
ssl_bump terminate all
"""


def valid_host_entry(entry: object) -> bool:
    return isinstance(entry, str) and bool(_HOST_ENTRY.match(entry.strip().lower()))


def clean_hosts(hosts: Iterable[object]) -> List[str]:
    """Valid, de-duplicated entries with redundant ones removed.

    ``.example.com`` already covers ``example.com`` and every subdomain; Squid
    warns about (and ignores) the overlap, so drop it here.
    """
    entries = list(dict.fromkeys(str(h).strip().lower() for h in hosts if valid_host_entry(h)))
    wild = {entry[1:] for entry in entries if entry.startswith(".")}
    kept = []
    for entry in entries:
        name = entry.lstrip(".")
        covered = any(name == parent or name.endswith("." + parent) for parent in wild)
        if entry.startswith("."):
            # Keep a wildcard unless a broader wildcard already covers it.
            if any(name != parent and name.endswith("." + parent) for parent in wild):
                continue
            kept.append(entry)
        elif not covered:
            kept.append(entry)
    return kept


def render_hosts(hosts: Iterable[object]) -> str:
    return "".join(f"{entry}\n" for entry in clean_hosts(hosts))


def render_config(port: int = 3128) -> str:
    return _CONFIG.format(
        port=int(port), log_dir=LOG_DIR, hosts_path=HOSTS_PATH, private=_PRIVATE_RANGES,
    )


MAX_REPORTED_HOSTS = 5
_MAX_REPORTED_LENGTH = 100


def parse_denied(access_log: str, allowed: Iterable[object] = ()) -> Tuple[str, ...]:
    """Host names Squid refused that approving could fix, for the "allow host" hint.

    The log is written by the sandboxed command's own requests, so every name
    here was chosen by that command: only well-formed names, only refusals of
    an HTTPS tunnel (``CONNECT name:443``) or of the TLS name inside one, a
    handful at most, and never a name that is already approved (those were
    refused for another reason, e.g. a private address).
    """
    approved = clean_hosts(allowed)

    def already_approved(name: str) -> bool:
        return any(
            name == entry.lstrip(".") or (entry.startswith(".") and name.endswith(entry))
            for entry in approved
        )

    found: List[str] = []
    for line in access_log.split("\n"):
        parts = line.split()
        if len(parts) < 3 or parts[1] != "CONNECT" or not parts[2].endswith(":443"):
            continue
        status = parts[0]
        candidates = []
        if "DENIED" in status:
            candidates.append(parts[2][:-4])
        elif status.startswith("NONE") and len(parts) > 3:
            # Tunnel opened, then cut: the TLS hello asked for another name.
            candidates.append(parts[3])
        for name in candidates:
            name = name.strip().lower().rstrip(".")
            if (
                len(name) <= _MAX_REPORTED_LENGTH
                and valid_host_entry(name)
                and not name.startswith(".")
                and not already_approved(name)
                and name not in found
            ):
                found.append(name)
    return tuple(found[:MAX_REPORTED_HOSTS])
