# Generated by Django 4.1.7 on 2025-07-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
