# Generated by Django 4.1.7 on 2025-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatroom_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
