# Generated by Django 5.2.8 on 2025-12-06 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of conversation')),
                ('participants', models.JSONField(default=list)),
                ('entities', models.JSONField(default=dict)),
                ('active_topics', models.JSONField(default=list)),
                ('message_count', models.IntegerField(default=0)),
                ('last_compressed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='chatbot.chatroom')),
                ('related_rooms', models.ManyToManyField(blank=True, to='chatbot.roomcontext')),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.TextField(help_text='What happened today in this room')),
                ('highlights', models.JSONField(default=list)),
                ('message_count', models.IntegerField(default=0)),
                ('participant_count', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='chatbot.roomcontext')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['room_context', '-date'], name='chatbot_dai_room_co_08b479_idx')],
                'unique_together': {('room_context', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('decision', 'Decision'), ('action_item', 'Action Item'), ('insight', 'Insight'), ('reference', 'Reference'), ('reminder', 'Reminder'), ('written', 'Written Note')], max_length=20)),
                ('content', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('source_message_id', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='chatbot.roomcontext')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_context', '-created_at'], name='chatbot_roo_room_co_904c78_idx'), models.Index(fields=['note_type', 'is_completed'], name='chatbot_roo_note_ty_a99425_idx')],
            },
        ),
    ]
