# Generated by Django 5.2.9 on 2025-12-20 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_roomcontext_dailysummary_roomnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomnote',
            name='source_message_content',
            field=models.TextField(blank=True, help_text='Full content of the pinned message'),
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('quota_window_start', models.DateTimeField(help_text='Start of the 10-hour quota window')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to='chatbot.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'quota_window_start'], name='chatbot_doc_user_id_436afb_idx'), models.Index(fields=['chatroom', '-uploaded_at'], name='chatbot_doc_chatroo_87c7b5_idx')],
            },
        ),
    ]
