# Generated by Django 5.2.9 on 2025-12-20 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_roomnote_source_message_content_documentupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='extracted_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata found during processing'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='processed_text',
            field=models.TextField(blank=True, help_text='Extracted text content from the document'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['status'], name='chatbot_doc_status_a692e0_idx'),
        ),
    ]
