# Generated by Django 5.2.9 on 2025-12-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_documentupload_extracted_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='has_ai_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
