# Generated by Codex on 2026-03-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_message_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReadState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chatbot.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.AddIndex(
            model_name='roomreadstate',
            index=models.Index(fields=['user', 'room'], name='chatbot_ro_user_id_4b07cb_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreadstate',
            index=models.Index(fields=['user', 'last_read_at'], name='chatbot_ro_user_id_9d6e64_idx'),
        ),
    ]
