# Generated by Codex on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_roomreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcontext',
            name='memory_facts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roomcontext',
            name='memory_preferences',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roomcontext',
            name='memory_episodes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roomcontext',
            name='memory_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
