# Generated by Django 4.2.27 on 2026-03-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_roomnote_is_private'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='chatbot_con_user_id_187fae_idx',
            old_name='chatbot_con_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='chatbot_con_user_id_aefbdb_idx',
            old_name='chatbot_con_user_id_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='chatbot_con_user_id_df9dd8_idx',
            old_name='chatbot_con_user_id_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='roomnote',
            new_name='chatbot_roo_is_arch_dd90a2_idx',
            old_name='chatbot_roo_is_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='roomreadstate',
            new_name='chatbot_roo_user_id_49eae5_idx',
            old_name='chatbot_ro_user_id_4b07cb_idx',
        ),
        migrations.RenameIndex(
            model_name='roomreadstate',
            new_name='chatbot_roo_user_id_986c77_idx',
            old_name='chatbot_ro_user_id_9d6e64_idx',
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomreadstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
