# Generated by Django 4.1.7 on 2025-10-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('encrypted_access_token', models.TextField(blank=True, null=True)),
                ('encrypted_refresh_token', models.TextField(blank=True, null=True)),
                ('calendly_user_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('webhook_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendly', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
