# Generated by Django 5.2.9 on 2025-12-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or brand name', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1', 'Just me'), ('2-5', '2-5 people'), ('6-10', '6-10 people'), ('11-25', '11-25 people'), ('26-50', '26-50 people'), ('50+', '50+ people')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g., Design, Development, Marketing, Consulting', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='{"email_notifications": true, "push_notifications": false, "digest_frequency": "daily"}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.IntegerField(default=0, help_text='Current onboarding step (0-6)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, help_text='Job title/role (e.g., Founder, Designer, Developer)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='{"twitter": "@handle", "linkedin": "url", "github": "url", "portfolio": "url"}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('personal', 'Personal Brand'), ('team', 'Team'), ('business', 'Business')], default='personal', help_text='Account type', max_length=20),
        ),
        migrations.CreateModel(
            name='GoalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.JSONField(blank=True, default=list, help_text='["grow_audience", "increase_revenue", "book_more_clients", etc.]')),
                ('custom_goals', models.TextField(blank=True, help_text='Free-form custom goals')),
                ('industry', models.CharField(blank=True, help_text='Primary industry (Design, Dev, Marketing, etc.)', max_length=100)),
                ('skills', models.JSONField(blank=True, default=list, help_text='["React", "SEO", "Copywriting", "B2B Sales"]')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('needs', models.JSONField(blank=True, default=list, help_text='["content_ideas", "engagement_strategies", "lead_generation", etc.]')),
                ('custom_needs', models.TextField(blank=True)),
                ('use_cases', models.JSONField(blank=True, default=list, help_text='["client_management", "team_collaboration", "social_monitoring", etc.]')),
                ('roadmap', models.JSONField(blank=True, default=list, help_text='[{"quarter": "Q1 2025", "goals": ["Launch newsletter"], "status": "in_progress"}]')),
                ('target_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue goal (e.g., $10,000 MRR)', max_digits=10, null=True)),
                ('target_followers', models.IntegerField(blank=True, help_text='Social media follower target', null=True)),
                ('target_clients', models.IntegerField(blank=True, help_text='Client acquisition target', null=True)),
                ('target_email_subscribers', models.IntegerField(blank=True, null=True)),
                ('ai_personalization_enabled', models.BooleanField(default=True, help_text='Allow AI to use goals for personalized suggestions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.workspace')),
            ],
        ),
    ]
